### ISSUE TITLE
[ASK] upload file example, 

### ISSUE THREAD

**Issue by codenoid** [ysbaddaden/selenium-webdriver-crystal#10]

**Comment by ysbaddaden** [comment]
Can you be a little more verbose in your request?

**Comment by ysbaddaden** [comment]
If you meant to upload a file, that probably requires a special call that isn't supported.

**Comment by codenoid** [comment]
i havent try, but i think it just `send_keys("/var/path/to/file.jpg")`

**Comment by ysbaddaden** [comment]
It looks like it, yes.
