### ISSUE TITLE
[ASK] How to enabling headless mode for firefox

### ISSUE THREAD

**Issue by codenoid** [ysbaddaden/selenium-webdriver-crystal#12]

**Comment by codenoid** [comment]
for firefox, add inside capabilites option
hope it's help ^^

```
args: ["-headless"]
```

**Comment by codenoid** [comment]
well, is jwp doesnt have `args` option on capabilities options ?

**Comment by ysbaddaden** [comment]
You mean you can't specify "args" or there is no way to pass the "-headless" CLI option to selenium?

In the past, I used to create a xvfb display, and run selenium server with DISPLAY env variable, so anything it starts will use it.

**Comment by codenoid** [comment]
actually @ysbaddaden , i just wanna know about memory usage in headless mode ^^

**Comment by codenoid** [comment]
i mean, wtf firefox eat 1GB RAM in VPS (with xvfb)

**Comment by ysbaddaden** [comment]
That should do the job —at least with Selenium 3.x (W3C Webdriver):

```crystal
capabilities = {
  "browserName" => "firefox",
  "moz:firefoxOptions": { "args" => ["-headless"] }
}
session = Selenium::Session.new(driver, capabilities, url: "about:blank")
```

**Comment by codenoid** [comment]
thank @ysbaddaden ^^ `"moz:firefoxOptions": { "args" => ["-headless"] }`
