### ISSUE TITLE
Avoid sleep, if possible

### ISSUE THREAD

**Issue by bararchy** [ysbaddaden/selenium-webdriver-crystal#13]
@ysbaddaden Is there a way to .wait for all pages to load? it seems risky to just sleep x sec and hope everything loads

**Comment by ysbaddaden** [comment]
I don't understand, there are no sleep for page load.

**Comment by bararchy** [comment]
I mean, when calling `session.url` it loads up relevant pages, now, if I won't "sleep" for a few sec (long page load) I will get partial info on the sources\html etc.. 

Is there a way to "block" until all resources has been downloaded?

**Comment by ysbaddaden** [comment]
AFAIK `session#url=` should only return when the page is loaded, that is the page `load` event is fired.

Does your page fires the `load` event *before* the page is actually rendered (e.g. JavaScript framework)? If so, you must inject a script that that will wait properly, which is out of scope of this driver.

**Comment by bararchy** [comment]
JavaScript indeed, I see, I'll try and see how to execute a waiting script
