### ISSUE TITLE
Error in casting when calling "text"

### ISSUE THREAD

**Issue by bararchy** [ysbaddaden/selenium-webdriver-crystal#31]
```crystal
cast from Nil to String failed, at /usr/lib/crystal/json/any.cr:187:5:187: cast from Nil to String failed, at /usr/lib/crystal/json/any.cr:187:5:187 (TypeCastError)
  from /usr/lib/crystal/json/any.cr:0:5 in 'as_s'
  from lib/selenium/src/webdriver/alert.cr:9:7 in 'text'

```

**Comment by ysbaddaden** [comment]
This is where it happens:
https://github.com/ysbaddaden/selenium-webdriver-crystal/blob/master/src/webdriver/alert.cr#L9

It used to work, but maybe W3C webdriver changed something on the protocol. Does the alert have a text? What's the JSON response?

**Comment by bararchy** [comment]
@ysbaddaden I'll add relevant debugging info ASAP, sorry for the delay
