### ISSUE TITLE
Fail to raise alert on <script>alert(1)</script>

### ISSUE THREAD

**Issue by bararchy** [ysbaddaden/selenium-webdriver-crystal#34]
Created a small HTML template with 

```crystal
server = HTTP::Server.new do |context|
  context.response.content_type = "text/html"
  html = <<-EOF
    <html>
      <head>
        <title>ALERT</title>
      </head>
      <body>
        <h1>Hello!</h1>
        <div>
          Hello and welcome to my site!
        </div>
        <script>alert(1)</script>
      </body>
    </html>
  EOF
  context.response.print(html)
end

server.bind_tcp 8000

server.listen
```

I did `@session.url` to the relevant address and tried both 
```crystal
Alert.new(@session)
# And
@session.alert
```

and they both raised `NoAlertOpenError`.

Is it just me? is this a bug in selenium? a different variant of `on_click` did work and raised an Alert object.

**Comment by ysbaddaden** [comment]
Maybe it has to do with the page *being loaded*? what about creating the alert in an `onload` event, or delaying in some manner? Or maybe this only works when we interact with the page (hence the `onclick`)?

**Comment by bararchy** [comment]
Knowing selenium and its shenanigans I tested sleep from 2s to 30s after the `session.url` call, sadly it seems to come from somewhere else in the selenium flow.
I'll try an `onload` but was surprised that the most basic scenario will work for a browser but not for selenium driven browser

**Comment by ysbaddaden** [comment]
That doesn't surprises me. An `alert()` inside a `<script>` is probably interrupting the page from loading properly, and webdriver don't get it. Running `alert()` *after* the page has loaded may be working, but the webdriver spec may tell that it may only be noticed when happening from an user interaction (I expect that).

**Comment by bararchy** [comment]
I see, in that case I will try and find a JS I can inject that will iterate all `document` alerts and raise them or something.
Thanks @ysbaddaden
