### ISSUE TITLE
Performance Benchmarks

### ISSUE THREAD

**Issue by 34code** [ysbaddaden/selenium-webdriver-crystal#4]
Any perf benchmarks of this against watir-webdriver?

**Comment by ysbaddaden** [comment]
Nope. I'm not sure it would be interesting, most of the slowness lies in Selenium itself.

**Comment by 34code** [comment]
I see. I would be happy to write tests for this project to see if it covers most/all of the functionality available in watir-webdriver (ruby) :)

**Comment by ysbaddaden** [comment]
I'm certainly missing tests, yes. If you can write more, that would be great!

The Webdriver protocol is very straightforward, and most of the usual features should be available, but some may not be implemented (grep TODO in `src`), or may not work: multiple windows, alert/confirm, select a file for upload, ...

**Comment by 34code** [comment]
got it.. I'll start writing some tests..

**Comment by ysbaddaden** [comment]
Closing. No update in a year.
