### ISSUE TITLE
Error trying to find element in a stale parent element

### ISSUE THREAD

**Issue by matthewmcgarvey** [ysbaddaden/selenium-webdriver-crystal#41]
DEBUG logs:

```text
REQUEST: POST /session/993659e2a8e9b61bbb2faedb9c635b10/element/0.7032859730331167-1/elements
{using: "css selector", value: "h1"}
RESPONSE: 200
{"sessionId" => "993659e2a8e9b61bbb2faedb9c635b10", "status" => 10, "value" => {"message" => "stale element reference: element is not attached to the page document\n  (Session info: headless chrome=81.0.4044.122)\n  (Driver info: chromedriver=81.0.4044.69 (6813546031a4bc83f717a2ef7cd4ac6ec1199132-refs/branch-heads/4044@{#776}),platform=Mac OS X 10.15.4 x86_64)"}}
```

Error:
```text
cast from Hash(String, JSON::Any) to Array(T) failed, at /usr/local/Cellar/crystal/0.34.0/src/json/any.cr:232:5:232 (TypeCastError)
         from /usr/local/Cellar/crystal/0.34.0/src/json/any.cr:232:5 in 'as_a'
         from lib/selenium/src/webdriver/session.cr:131:7 in 'find_elements'
```

Relevant code: https://github.com/ysbaddaden/selenium-webdriver-crystal/blob/bda2fd406c1a118251c5a2883f1e1f3af242116e/src/webdriver/session.cr#L124-L131

Because the status was still 200 and the value of the `value` key in the response body was not an array, it failed. My guess is that this was a change from what this library was coded to and has changed in the switch to the W3C spec.

Ideally this would be handled by checking more than the response status.

Possible solution area: https://github.com/ysbaddaden/selenium-webdriver-crystal/blob/bda2fd406c1a118251c5a2883f1e1f3af242116e/src/webdriver.cr#L61-L66

**Comment by ysbaddaden** [comment]
Indeed, I suppose the logic changed again, and it always responds with 200 or whatever now. I guess what must be checked too is `status` to know whether the query was successful?

If someone can dig the huge Webdriver SPEC...
