### ISSUE TITLE
Error finding an element

### ISSUE THREAD

**Issue by Xosmond** [ysbaddaden/selenium-webdriver-crystal#5]
Im getting this error when trying to find an element:

`table = session.find_element(:css, "div.APLI_inernalcontent")`

```
in lib/selenium/src/webdriver/session.cr:100: can't restrict Nil to WebElement

    def find_element(by, selector, parent : WebElement = nil)
                                                       ^
```

How can I solve it?

PD: I did a monkey patching, to create another method:

```
module Selenium
  class Session
    def from_parent_find_element(by, selector)
      url = "/element"
      value = post(url, {
        using: WebElement.locator_for(by),
        value: selector
      })
      if value.as(Hash).has_key? "ELEMENT"
        WebElement.new(self, value.as(Hash))
      else
        nil
      end
    end
  end
end
```

The last conditional is because when the element is not found selenium on the current version send a message and not thrown an error.

PD2: I recommend to merge the branch that solves the "as" syntax problem.

**Comment by ysbaddaden** [comment]
Fixed in e5710b57fa78d2cec98cd951fdd1cad99e7226d0

Please note that this shard implements the obsolete JsonWriteProtocol of Selenium Webdriver, as of Selenium 2.48 for example, not the new W3C Webdriver spec as per Selenium 3.5 and Firefox 55.
