### ISSUE TITLE
connect: Cannot assign requested address

### ISSUE THREAD

**Issue by Xosmond** [ysbaddaden/selenium-webdriver-crystal#7]
This issue is particular because its only happens on a **Docker Container** ( on Linux(vps) and Mac works fine).

The program is basic to show the error:

```crystal
require "selenium/webdriver"

capabilities = {
  browserName: "chrome",
  platform: "ANY"
}

driver = Selenium::Webdriver.new
session = Selenium::Session.new(driver, capabilities, capabilities, "http://google.com")
sleep 1

puts "Do the job"
session.stop
```

The error is:

```
connect: Cannot assign requested address (Errno)
0x48c197: *CallStack::unwind:Array(Pointer(Void)) at ??
0x53976f: initialize at /usr/local/share/crystal-0.23.1-3/src/socket/tcp_socket.cr 71:15
0x537aa4: new at /usr/local/share/crystal-0.23.1-3/src/socket/tcp_socket.cr 27:3
0x529c49: socket at /usr/local/share/crystal-0.23.1-3/src/http/client.cr 652:5
0x529a5d: exec_internal_single at /usr/local/share/crystal-0.23.1-3/src/http/client.cr 500:5
0x526d7c: exec_internal at /usr/local/share/crystal-0.23.1-3/src/http/client.cr 486:5
0x526c62: exec at /usr/local/share/crystal-0.23.1-3/src/http/client.cr 483:5
0x526980: exec at /usr/local/share/crystal-0.23.1-3/src/http/client.cr 586:5
0x526929: post at /usr/local/share/crystal-0.23.1-3/src/http/client.cr 329:3
0x525672: post at /home/curosmond/app/lib/selenium/src/webdriver.cr 49:9
0x52a9be: initialize at /home/curosmond/app/lib/selenium/src/webdriver/session.cr 29:7
0x52a862: new at /home/curosmond/app/lib/selenium/src/webdriver/session.cr 24:5
0x4724be: __crystal_main at /home/curosmond/app/herllo.cr 9:1
0x485299: main at /usr/local/share/crystal-0.23.1-3/src/main.cr 12:15
0x7fc4efb07830: __libc_start_main at ??
0x471bc9: _start at ??
0x0: ??? at ??
```

The following code with HTTP::Client works fine:

```crystal
require "http/client"

response = HTTP::Client.get  "http://google.com"
sleep 1

puts "Do the job"
```

I thought the problem was file/socket descriptors, but, its only a request and I have configured 262144 file descriptors. 

Any idea on whats the problem?

**Comment by Xosmond** [comment]
After some change I decided to use selenium chrome docker image and everything works. So I think the program couldn't connect to selenium.

**Comment by ysbaddaden** [comment]
Yup, that's a weird error. The driver tries to connect a TCP socekt to the Selenium server on `http://localhost:4444/wd/hub` but `connect` fails with EADDRNOTAVAIL. Maybe http://www.toptip.ca/2010/02/linux-eaddrnotavail-address-not.html can help understand the issue?

**Comment by Xosmond** [comment]
After thinking about it. Maybe the problem was that the program was trying to connect to selenium and every time it tried, the connection went into TIME_WAIT (or some other status that kept an open connection for some time) because of some problem on selenium standalone server.

So the selenium was using all ports and keeping them up on TIME_WAIT.

Thats the only reason i can imagine.

PD: TIME_WAIT is only an example, i didnt make a debug.

**Comment by Xosmond** [comment]
After thinking about it. Maybe the problem was that the program was trying to connect to selenium and every time it tried, the connection went into TIME_WAIT (or some other status that kept an open connection for some time) because of some problem on selenium standalone server.

So the selenium and the crystal program were using all ports and keeping them up on TIME_WAIT becaouse of selenium standalone server.

Thats the only reason that can explain the situation. 

PD: TIME_WAIT is only an example, i didnt make a debug.
