### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by faustinoaq** [ysbaddaden/selenium-webdriver-crystal#9]
Hi @ysbaddaden  We are using this shard on [System Test Framework](https://github.com/amberframework/amber-spec#system-test-framework) for Amber Framework,

Almost a year since the latest tag release, some important commits have been published on master and some issues has been solved, also compatibility with latest crystal version have been fixed.

So, please, Can you create a new tag/version to avoid  `master` on our `shard.yml` ? 😄 

Thank you for this shard!

**Comment by ysbaddaden** [comment]
Here you go: https://github.com/ysbaddaden/selenium-webdriver-crystal/releases/tag/v0.3.0
